# Database Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Drivercom.mysql.cj.jdbc.Drivercom.mongodb.client.MongoClient
    url: jdbc:postgres://localhost:54323306/deskdemo_db
    username: ${DB_USER:root}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialectorg.hibernate.dialect.MySQLDialect
