spring:
  datasource:
    url: jdbc:postgres://localhost:54323306/deskdemo_db
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.deskdemo: DEBUG
